# Generated by Django 5.0.4 on 2024-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('list_of_students', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SAGBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('list_of_students', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('income', models.IntegerField()),
                ('class10_percent', models.FloatField()),
                ('class12_percent', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10)),
                ('documents', models.JSONField()),
            ],
        ),
    ]
