# Generated by Django 5.0.4 on 2024-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='documents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
