# Generated by Django 5.0.4 on 2024-09-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_students_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialbureau',
            name='list_of_students',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sagbureau',
            name='list_of_students',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
