# Generated by Django 5.0.4 on 2024-09-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_financialbureau_list_of_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialbureau',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sagbureau',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
