# Generated by Django 5.0.4 on 2024-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_financialbureau_name_sagbureau_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
