# Generated by Django 5.0.4 on 2024-09-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_students_address_students_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
    ]
