# Generated by Django 5.0.4 on 2024-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_students_feedback_students_feedback_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
