# Generated by Django 5.0.4 on 2024-09-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_students_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
