# Generated by Django 5.0.4 on 2024-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_students_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
